VERSIONS.md
lib/zigler/doc/parser.ex
lib/zigler/doc/retriever.ex

make zigdocs tag zig code with url links (at least, for github).

Fix beam code lines

---

lib/zigler/zig.ex

- BSD uses amd64 for x86_64
- add a helpful error message for future architectures

add further architecture support

---

lib/zig.ex
lib/zig/command.ex
lib/zig/compiler.ex

fixed:
- add win{32,64} arch
- increased zig download tiimeout to 10 min
- path not being escaped
- use windows built-in `tar` instead of `unzip`

fix: :bug: first steps to prepare zig to build on windows

---

test/integration/strategies/yielding_nif_test.exs

Needs testing on other platforms to confirm.
TLDR: use monotonic time calculations everywhere. Remind people to append
`+C multi_time_warp` in `ERL_FLAGS` always.
By default, erts uses the pre-timewarp calculation of VM time, which is effectively
broken by design, and is still the default because changing the VM's handling of
time is a significant intrusion.
Elixir's `DateTime.utc_now/0` function calls on `System.os_time/0` which eventually
calls [system_time/0] which runs into the VM's fluid and confused notion of time
while running NIFs.
Ideally, you should always include `+C multi_time_warp` in `ERL_FLAGS`, anyway,
but by using `System.monotonic_time/1` we avoid the inherent problems in
`DateTime.utc_now/0` related to time warping.
For more info, read: …

tests: use monotonic_time/1 to handle Time Warps correctly

---

lib/zig/command.ex
mix.exs
mix.lock

Given httpc does _not_ ship with secure https defaults [1] we include and check against checksums.
I decided not to include ssl & inets (which we need) in `:extra_applications` given we can use the library without downloading pre-built binaries.
[1] https://blog.voltone.net/post/23

Replace Mojito with httpc

---

lib/zig/nif/yielding.ex

This makes them surface and prevents crashing when trying to access the result of an exception-terminated yielding NIF.

yielding: propagate exceptions from yield_env to the process env

---

lib/zig/nif/yielding.ex

As indicated in the comment, this does not cover lists and map.

yielding: copy the response back to the process env

---

lib/zig/nif/yielding.ex

This is the other place where our result can be returned.
This must be done here and not in the harness function because the valid target env is actually the one that is passed to the rescheduler, since `parent_env` in the harness function can be stale.
Also fix the previous PR moving the check for exception in the correct place.

yielding: copy the result in the correct env in rescheduler too

---

priv/beam/beam.zig

Remove the NoOp implementation and actually call alignedFree

beam.zig: implement free for large_beam_allocator

---

lib/zig/typespec.ex
test/integration/strategies/yielding_nif_test.exs

Fix typespec ast for elixir 1.14, skip test that causes core dump

---

.github/workflows/elixir.yml

Hex doesn't build 23.0 for ubuntu-latest, which causes CI to fail. By pinning on 20.04 we can get CI to work. See
https://repo.hex.pm/builds/otp/ubuntu-20.04/builds.txt and
https://repo.hex.pm/builds/otp/ubuntu-22.04/builds.txt

Fix linux CI by pinning ubuntu version

---

priv/beam/beam.zig

Allows using it as `beam.BeamMutex`.

Export mutex

---

lib/zig/command.ex
mix.exs

By using application.compile_env we can guarantee that this module
gets recompiled when someone change zigler's config.
Bumps required elixir version to 1.10, since `Application.compile_env/3`.
Notice that Zigler **is already incompatible** with elixir 1.9 due to existing
`Application.compile_env/3` calls.

Don't use Application.get_env/3 in module body

---

priv/beam/stub_erl_nif.zig

This made compilation fail in the second example of the docs

stub_erl_nif: fix enif_make_int64 parameter type

---

lib/zig/assembler.ex

Otherwise absolute paths will be appended to the project path.

Correctly expand absolute paths for `link_lib`

---

README.md
VERSIONS.md
installer/mix.exs
installer/mix.tasks/zig.get.ex
lib/zig/templates/build.zig.eex
lib/zig/type/enum.ex
mix.exs
mix.lock
test/_support/compiler.ex
test/_support/spec_template.ex

Mostly version bumping plus a single line change in the `build.zig` template.
Also cleanup Elixir 1.17 warnings.

Update to Zig 0.13

---

lib/zig/_c.ex
lib/zig/templates/build.zig.eex
mix.exs

Allows our project to build with the upgraded zigler.
* Guides are not available in published package, adapted the code to be able to deal with that.
* `addObjectFile` expects a `LazyPath`
* Correctly expand path to `include_dirs`

Various small fixes

---

lib/zig/_c.ex
lib/zig/target.ex
lib/zig/templates/build.zig.eex

This PR does 2 things:
* Allows passing `library_dirs` option to the `c` config when `use`ing `Zig`
* Removes the requirement that `Mix.target() == :host` to update the target using environment variables

Add library_dirs and update target arch rules

---

lib/zig.ex
lib/zig/compiler.ex

When I first tried zig_code_path, I tried using Path.join in the `use` opts.
This raised and I settled for a relative path (which I realize is the expected
code path).
Even if this change is not accepted, we can raise in a more informative way
in the new `if is_binary(path)` conditional.
Also, the put_attribute call makes it so that the code recompiles whenever
the zig source changes.

feat: zig_code_path quality-of-life improvements

---

lib/zig/compiler.ex

We should only be attempting to recursively parse `.zig` files.
Closes #508

Stop attempting to parse @embedFile as zig file
